dist: Focal
sudo: required

stages:
    - test-PCSC-packaging

jobs:
    include:
    - stage: test-PCSC-packaging
    script:
        - cd pcsc-lite-max-readers-macro-update/
        - chmod +x script.sh
        - sudo ./script.sh
