/**
 * Intro messages are displayed when the user presses the help button
 */
export class IntroMessage {
	static HEADER_BUTTONS =
		"To navigate on the website, use the header buttons. You can choose between the home (status) page, supported MPC protocols, and the ping page for performance testing.";
	static PROTOCOL_NAME =
		"This is the currently selected protocol. Using the control panel on this page won't affect other protocols.";
	static HEADER_DRAWER =
		"To navigate on the website, use the main menu. You can choose between the home (status) page and the supported MPC protocols.";
	static HOME_PAGE_STATUS =
		"This page contains information about the MPCOP server.";
	static PUBLIC_KEY_FIELD =
		"This field contains the public key encoded in hex format. You can not modify this field - it is filled automatically after the public key has been generated by the protocol.";
	static DATA_OUTPUT_FIELD =
		'Here you can find outputs of performed operation, e.g. a signature after the "sign" operation.';
	static INPUT_DATA_FIELD =
		'In case the selected operation takes arguments, e.g. the "sign" operation takes data to sign, you can input a hex-encoded string and it will be passed as an input argument to the protocol. We have already filled in some test data (a SHA2 hash of the word "password").';
	static PROTOCOL_BUTTONS =
		"These are the operations that can be performed with the currently-selected protocol. Hover above individual buttons for more thorough description";
	static DEBUG_BUTTON =
		"You can open a debug console by clicking the `debug` buton. The debug console reveals what's going on under the hood and also shows a detailed history of operations.";
	static PROTOCOL_INFO =
		"The results of individual operations as well as any warnings and information messages will be displayed here.";
	static PROTOCOL_SETUP =
		"The protocol can be customized using this setup area. Be careful, though. Customizing the protocol can irreversibly erase cryptographic secrets!";
}
