export class IntroMessage {
	static HEADER_BUTTONS =
		"These are the MPC protocols that are currently supported by MPCOP. To suggest support of a new one, create an issue on GitHub.";
	static HEADER_DRAWER = "You can select protocols by tapping this button."
	static HOME_PAGE_STATUS =
		"This page contains information about the MPCOP state.";
	static PUBLIC_KEY_FIELD =
		"This is the field that contains the public key encoded in hex format. You can not modify this field - it is filled automatically after the public key has been generated by the protocol.";
	static DATA_OUTPUT_FIELD =
		"Here you can find outputs of performed operation, e.g. a signature after the `sign` operation.";
	static INPUT_DATA_FIELD =
		"In case the selected operation takes arguments, e.g. the `sign` operation takes data to sign, you can input a hex-encoded string here and it will be passed as an input argument to the protocol.";
	static PROTOCOL_BUTTONS =
		"These are the operations that can be performed with the currently-selected protocol. Hover above individual buttons for more thorough description";
	static DEBUG_BUTTON =
		"You can open a debug console by clicking the `debug` buton. The debug console reveals what's going on under the hood and also shows a detailed history of operations.";
	static PROTOCOL_INFO =
		"The results of individual operations as well as any warnings and information messages will be displayed here. For example, you may have seen a warning stating the public key has not been generated yet, on the initial MPCOP run, .";
	static PROTOCOL_SETUP =
		"The protocol can be customized using this setup area. Be careful, though. Customizing the protocol can irreversible erase cryptographic secrets!";
}
